// GENERATED by scripts/contracts.ps1 from contracts/request-types.json. Do not edit.
// Source version: 1
namespace WarCommand.Agent.Core.Contracts;

public static class RoleIds
{
    public const string Mortar = "mortar";
    public const string Artillery = "artillery";
    public const string AirSupport = "air_support";
    public const string AirTransport = "air_transport";
    public const string GroundTransport = "ground_transport";
    public const string Logistics = "logistics";
    public const string Medic = "medic";
    public const string Armor = "armor";
    public const string Recon = "recon";
    public const string Engineer = "engineer";
    public const string Command = "command";
}

public static class RequestTypeIds
{
    public const string MortarFire = "mortar_fire";
    public const string ArtilleryFire = "artillery_fire";
    public const string AirStrike = "air_strike";
    public const string TransportMove = "transport_move";
    public const string AirTransportMove = "air_transport_move";
    public const string Extraction = "extraction";
    public const string Resupply = "resupply";
    public const string MedicRequest = "medic_request";
    public const string ArmorSupport = "armor_support";
    public const string ReconRequest = "recon_request";
    public const string EngineerRequest = "engineer_request";
    public const string IntelMarker = "intel_marker";
}

public static class GrammarRules
{
    public const int MaxSlots = 9;
    public const int SlotQuarantineSeconds = 20;
    public const int AcceptAllCap = 3;
    public const double MinIntentConfidence = 0.6;
    public const int PreviewHoldMs = 1200;
    public const int RecallWindowSeconds = 5;
    public const int AwaitingPointTimeoutSeconds = 20;
    public const int TapMaxMs = 180;
}
