// GENERATED by scripts/contracts.ps1 from contracts/request-types.json. Do not edit.
// Source version: 3
namespace WarCommand.Agent.Core.Contracts;

public static class RoleIds
{
    public const string Mortar = "mortar";
    public const string Artillery = "artillery";
    public const string Armor = "armor";
    public const string AirSupport = "air_support";
    public const string Stingray = "stingray";
    public const string Infantry = "infantry";
    public const string Sniper = "sniper";
    public const string Medic = "medic";
    public const string GroundTransport = "ground_transport";
    public const string AirTransport = "air_transport";
    public const string Builder = "builder";
    public const string Command = "command";
}

public static class RequestTypeIds
{
    public const string Resupply = "resupply";
    public const string GearArmor = "gear_armor";
    public const string GearHelmet = "gear_helmet";
    public const string GearCamo = "gear_camo";
    public const string UtilityMedical = "utility_medical";
    public const string UtilityTactical = "utility_tactical";
    public const string UtilityRecon = "utility_recon";
    public const string UtilityVehicle = "utility_vehicle";
    public const string WeaponRifle = "weapon_rifle";
    public const string WeaponSmg = "weapon_smg";
    public const string WeaponShotgun = "weapon_shotgun";
    public const string WeaponLmg = "weapon_lmg";
    public const string WeaponMarksman = "weapon_marksman";
    public const string WeaponSniper = "weapon_sniper";
    public const string WeaponBow = "weapon_bow";
    public const string WeaponSidearm = "weapon_sidearm";
    public const string WeaponLauncher = "weapon_launcher";
    public const string Ammo9mm = "ammo_9mm";
    public const string Ammo45 = "ammo_45";
    public const string Ammo50ae = "ammo_50ae";
    public const string AmmoColt = "ammo_colt";
    public const string Ammo556 = "ammo_556";
    public const string Ammo545 = "ammo_545";
    public const string Ammo762x39 = "ammo_762x39";
    public const string Ammo762x54 = "ammo_762x54";
    public const string Ammo308 = "ammo_308";
    public const string Ammo50cal = "ammo_50cal";
    public const string AmmoBuck = "ammo_buck";
    public const string AmmoSlug = "ammo_slug";
    public const string Ammo40mm = "ammo_40mm";
    public const string Ammo155mm = "ammo_155mm";
    public const string Ammo84mm = "ammo_84mm";
    public const string Ammo93mm = "ammo_93mm";
    public const string Ammo35x228mm = "ammo_35x228mm";
    public const string Ammo120heat = "ammo_120heat";
    public const string AmmoArrow = "ammo_arrow";
    public const string AmmoBatt = "ammo_batt";
    public const string ShellMission = "shell_mission";
    public const string ArmorSupport = "armor_support";
    public const string CloseAir = "close_air";
    public const string StingrayFire = "stingray_fire";
    public const string AirMove = "air_move";
    public const string AirExtract = "air_extract";
    public const string GroundMove = "ground_move";
    public const string GroundExtract = "ground_extract";
    public const string FireTeam = "fire_team";
    public const string Overwatch = "overwatch";
    public const string MedicRequest = "medic_request";
    public const string SmokeScreen = "smoke_screen";
    public const string VehicleDefense = "vehicle_defense";
    public const string VehicleRefuel = "vehicle_refuel";
    public const string VehicleRepair = "vehicle_repair";
    public const string BuildFob = "build_fob";
    public const string BuildApcSpawn = "build_apc_spawn";
    public const string BuildDefenses = "build_defenses";
    public const string BuildWeapons = "build_weapons";
    public const string BuildRepairs = "build_repairs";
    public const string BuildBuilders = "build_builders";
    public const string BuildPlanners = "build_planners";
    public const string BuildDrill = "build_drill";
}

public static class GrammarRules
{
    public const int MaxSlots = 9;
    public const int AcceptAllCap = 3;
    public const double MinIntentConfidence = 0.6;
    public const int PreviewHoldMs = 1200;
    public const int RecallWindowSeconds = 5;
    public const int AwaitingPointTimeoutSeconds = 20;
    public const int TapMaxMs = 180;
    public const int InviteCodeDigits = 6;
    public const double AmbiguityMargin = 0.15;
    // Slots are least-recently-released. There is no quarantine: it capped board
    // throughput at 9 rows per 20 s, below what providers clear.
    // See Decision_WarCommandSlotsAreLeastRecentlyReleased.
    public const int LowPrioritySlotResidencySeconds = 60;
    public const double CoalesceRadiusUnits = 0.5;
    public const int CoalesceWindowSeconds = 60;
}

public static class SupplyKinds
{
    public const string Building = "building";
    public const string Ammo = "ammo";
    public const string Fuel = "fuel";
    public const string Mechanical = "mechanical";
    public const string Hammers = "hammers";
    public const string Fob = "fob";
}

public static class StructureKinds
{
}

// A verb that is not terminal leaves the request in its current state.
// splash and rounds out are rounds_away, never done.
// See Convention_WarCommandSplashIsNotDone.
public static class TerminalVerbs
{
    public const string Done = "done";
}
